services:
    sonata.admin.comment:
        class: AppBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Comment" }
        arguments:
            - ~
            - AppBundle\Entity\Comment
            - ~


    sonata.admin.post:
        class: AppBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - AppBundle\Entity\Post
            - ~
          #  - AppBundle:CRUD
        calls:
            - [ setTranslationDomain, [AppBundle]]
            - [ addChild , ['@sonata.admin.comment']]
